AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  game-tracker

  Sample SAM Template for game-tracker
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GameTrackerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: game-tracker/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Events:
        GameTrackerService:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/contacts/finalize
            Method: put

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GameTrackerApi:
    Description: "API Gateway endpoint URL for Prod stage for Game Tracker function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GameTrackerFunction:
    Description: "Game Tracker Lambda Function ARN"
    Value: !GetAtt GameTrackerFunction.Arn
  GameTrackerFunctionIamRole:
    Description: "Implicit IAM Role created for Game Tracker function"
    Value: !GetAtt GameTrackerFunctionRole.Arn
